name=input("Hi! What is your name? ")
if name=="Zoe":
    print("No way, we have the same name! Let's play madlibs!")
else:
    print(f"Let's play madlibs {name}!")
input("")
place1=input("Give me a place: ")
print("")
character1=input("Now give me a name: ")
print("")
animal1=input("Give me an animal: ")
print("")
verb1=input("Give me a verb ending in ing: ")
print("")
bodypart1=input("Now a body part: ")
print("")
job1=input("Now a job: ")
print("")
feeling1=input("Now give me a feeling: ")
print("")
print("-------------------------------------------------------------------------")
input(f"Once upon a time in {place1}, {character1} the {animal1} went {verb1}.")
input(f"But while he was doing that, he broke his {bodypart1}!")
input(f"He was rushed to the {job1}'s!")
input(f"{character1} has been best friends with the {job1} ever since they saved his life.")
input(f"{character1} has been feeling {feeling1} since then!")